# Generated by Django 4.0.3 on 2022-04-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dataviz', '0002_datastudent_filemodel_delete_bilanannuel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='credit',
            field=models.IntegerField(default=0.0, max_length=2),
        ),
    ]
