# Generated by Django 4.0.3 on 2022-04-08 15:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Dataviz', '0004_alter_matiere_credit'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilePV',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date_save', models.DateField(auto_now_add=True)),
                ('file_model', models.FileField(max_length=200, upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('note_cc', models.FloatField(default=0.0, max_length=200)),
                ('note_tp', models.FloatField(default=0.0, max_length=200)),
                ('note_sn', models.FloatField(default=0.0, max_length=200)),
                ('note_moy', models.FloatField(default=0.0, max_length=200)),
                ('credit', models.IntegerField(default=0.0)),
                ('decision', models.CharField(max_length=5, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='note',
            name='matiere',
        ),
        migrations.RemoveField(
            model_name='note',
            name='student',
        ),
        migrations.RemoveField(
            model_name='filemodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='groupe',
            name='libelle',
        ),
        migrations.RemoveField(
            model_name='matiere',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='matiere',
            name='decision',
        ),
        migrations.RemoveField(
            model_name='matiere',
            name='libelle',
        ),
        migrations.RemoveField(
            model_name='student',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='student',
            name='matricule',
        ),
        migrations.RemoveField(
            model_name='student',
            name='surname',
        ),
        migrations.AddField(
            model_name='student',
            name='annee',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='cycle',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='filiere',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='niveau',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='mot_de_passe',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='DataStudent',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.AddField(
            model_name='notes',
            name='matiere',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Dataviz.matiere'),
        ),
        migrations.AddField(
            model_name='notes',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Dataviz.student'),
        ),
    ]
