# Generated by Django 4.0.3 on 2022-04-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dataviz', '0005_filepv_notes_remove_note_matiere_remove_note_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupe',
            name='libelle',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matiere',
            name='libelle',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
