# Generated by Django 4.0.3 on 2022-04-09 14:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Dataviz', '0008_alter_groupe_id_alter_matiere_id_alter_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('annee', models.CharField(max_length=10, null=True)),
                ('filiere', models.CharField(max_length=10, null=True)),
                ('cycle', models.CharField(max_length=10, null=True)),
                ('niveau', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='annee',
        ),
        migrations.RemoveField(
            model_name='student',
            name='cycle',
        ),
        migrations.RemoveField(
            model_name='student',
            name='filiere',
        ),
        migrations.RemoveField(
            model_name='student',
            name='niveau',
        ),
        migrations.CreateModel(
            name='Classe_Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dataviz.classe')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dataviz.student')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='classe',
            field=models.ManyToManyField(through='Dataviz.Classe_Student', to='Dataviz.classe'),
        ),
    ]
