# Generated by Django 4.0.4 on 2022-04-22 21:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Dataviz', '0009_classe_remove_student_annee_remove_student_cycle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileBilan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('annee', models.CharField(max_length=200, null=True)),
                ('date_save', models.DateField(auto_now_add=True)),
                ('file_bilan', models.FileField(max_length=200, upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='FileRattrapage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('annee', models.CharField(max_length=200, null=True)),
                ('date_save', models.DateField(auto_now_add=True)),
                ('file_rattrapage', models.FileField(max_length=200, upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='MoyenneS1',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('annee', models.CharField(max_length=10, null=True)),
                ('moy_s1', models.FloatField(default=0.0, max_length=200)),
                ('mgp', models.FloatField(default=0.0, max_length=200)),
                ('credit', models.FloatField(default=0.0, max_length=200)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Dataviz.student')),
            ],
        ),
        migrations.CreateModel(
            name='MoyenneS2',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('annee', models.CharField(max_length=10, null=True)),
                ('moy_s2', models.FloatField(default=0.0, max_length=200)),
                ('mgp', models.FloatField(default=0.0, max_length=200)),
                ('credit', models.FloatField(default=0.0, max_length=200)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Dataviz.student')),
            ],
        ),
        migrations.RenameField(
            model_name='filepv',
            old_name='name',
            new_name='annee',
        ),
        migrations.AlterField(
            model_name='notes',
            name='credit',
            field=models.FloatField(default=0.0, max_length=200),
        ),
        migrations.DeleteModel(
            name='Moyenne',
        ),
    ]
