# Generated by Django 4.0.3 on 2022-04-23 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dataviz', '0011_matiere_semestre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filepv',
            old_name='file_model',
            new_name='file_pv',
        ),
    ]
