# Generated by Django 4.0.3 on 2022-04-23 08:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Dataviz', '0012_rename_file_model_filepv_file_pv'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=200, null=True)),
                ('mot_de_passe', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='classe',
            name='annee',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='classe',
            name='cycle',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='classe',
            name='filiere',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
