# Generated by Django 4.0.3 on 2022-04-30 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dataviz', '0015_matiere_classe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classe',
            name='annee',
        ),
        migrations.RemoveField(
            model_name='filemodel',
            name='date_save',
        ),
        migrations.AddField(
            model_name='classe_student',
            name='annee',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
