# Generated by Django 4.0.3 on 2022-04-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dataviz', '0016_remove_classe_annee_remove_filemodel_date_save_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filebilan',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='filepv',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='filerattrapage',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
