# Generated by Django 4.0.3 on 2022-04-30 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dataviz', '0018_alter_classe_id_alter_filebilan_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filebilan',
            name='name',
        ),
        migrations.RemoveField(
            model_name='filepv',
            name='name',
        ),
        migrations.RemoveField(
            model_name='filerattrapage',
            name='name',
        ),
    ]
