# Generated by Django 4.0.3 on 2022-04-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dataviz', '0020_alter_filebilan_date_save_alter_filepv_date_save_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe_student',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
