# Generated by Django 4.0.3 on 2022-04-30 13:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Dataviz', '0021_alter_classe_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe_student',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
