# Generated by Django 4.0.3 on 2022-05-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dataviz', '0024_alter_student_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileBilan',
        ),
        migrations.DeleteModel(
            name='FileRattrapage',
        ),
        migrations.RemoveField(
            model_name='filepv',
            name='annee',
        ),
        migrations.RemoveField(
            model_name='filepv',
            name='date_save',
        ),
        migrations.AddField(
            model_name='moyennes1',
            name='credit_total',
            field=models.FloatField(default=0.0, max_length=200),
        ),
        migrations.AddField(
            model_name='moyennes2',
            name='credit_total',
            field=models.FloatField(default=0.0, max_length=200),
        ),
    ]
